name: FINE
dependencies:
- python=3.6
- conda-forge::gdal=2.4.1
- conda-forge::geopandas
- conda-forge::jupyter
- conda-forge::notebook
- pip
- descartes
- glpk
- openpyxl
- matplotlib
- xlrd==1.2.0
- pyomo
- numpy
- pandas
- GPyOpt
- networkx
- scipy
- pwlf
- pyDOE
- sphinx_rtd_theme
- scikit-learn
- pip:
    - tsam